// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/dto.dart';
import 'api/vault.dart';
import 'api/vault_ephemeral.dart';
import 'api/vault_projections.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActiveMedDto dco_decode_active_med_dto(dynamic raw);

  @protected
  AllergyItemDto dco_decode_allergy_item_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ConsentDto dco_decode_box_autoadd_consent_dto(dynamic raw);

  @protected
  DocumentSummaryDto dco_decode_box_autoadd_document_summary_dto(dynamic raw);

  @protected
  EncounterSummaryDto dco_decode_box_autoadd_encounter_summary_dto(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ChronicConditionDto dco_decode_chronic_condition_dto(dynamic raw);

  @protected
  ClaimResultDto dco_decode_claim_result_dto(dynamic raw);

  @protected
  ConfirmedStatusDto dco_decode_confirmed_status_dto(dynamic raw);

  @protected
  ConsentDto dco_decode_consent_dto(dynamic raw);

  @protected
  DocumentDetailDto dco_decode_document_detail_dto(dynamic raw);

  @protected
  DocumentSummaryDto dco_decode_document_summary_dto(dynamic raw);

  @protected
  EmergencyCardDto dco_decode_emergency_card_dto(dynamic raw);

  @protected
  EncounterSummaryDto dco_decode_encounter_summary_dto(dynamic raw);

  @protected
  ExportResultDto dco_decode_export_result_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IcloudStatusDto dco_decode_icloud_status_dto(dynamic raw);

  @protected
  ImportOutcomeDto dco_decode_import_outcome_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ActiveMedDto> dco_decode_list_active_med_dto(dynamic raw);

  @protected
  List<AllergyItemDto> dco_decode_list_allergy_item_dto(dynamic raw);

  @protected
  List<ChronicConditionDto> dco_decode_list_chronic_condition_dto(dynamic raw);

  @protected
  List<ConfirmedStatusDto> dco_decode_list_confirmed_status_dto(dynamic raw);

  @protected
  List<DocumentSummaryDto> dco_decode_list_document_summary_dto(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProxyLabDto> dco_decode_list_proxy_lab_dto(dynamic raw);

  @protected
  List<ProxyLabPointDto> dco_decode_list_proxy_lab_point_dto(dynamic raw);

  @protected
  List<ProxyMedDto> dco_decode_list_proxy_med_dto(dynamic raw);

  @protected
  List<ProxyProblemDto> dco_decode_list_proxy_problem_dto(dynamic raw);

  @protected
  List<TimelineGroupDto> dco_decode_list_timeline_group_dto(dynamic raw);

  @protected
  List<TrendPointDto> dco_decode_list_trend_point_dto(dynamic raw);

  @protected
  List<TrendSeriesDto> dco_decode_list_trend_series_dto(dynamic raw);

  @protected
  List<VisitLabDto> dco_decode_list_visit_lab_dto(dynamic raw);

  @protected
  List<VisitRecordDto> dco_decode_list_visit_record_dto(dynamic raw);

  @protected
  OcrPpResultDto dco_decode_ocr_pp_result_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  PatientProfileDto dco_decode_patient_profile_dto(dynamic raw);

  @protected
  ProxyLabDto dco_decode_proxy_lab_dto(dynamic raw);

  @protected
  ProxyLabPointDto dco_decode_proxy_lab_point_dto(dynamic raw);

  @protected
  ProxyMedDto dco_decode_proxy_med_dto(dynamic raw);

  @protected
  ProxyProblemDto dco_decode_proxy_problem_dto(dynamic raw);

  @protected
  ProxySummaryDto dco_decode_proxy_summary_dto(dynamic raw);

  @protected
  QrShareDto dco_decode_qr_share_dto(dynamic raw);

  @protected
  (PlatformInt64, String) dco_decode_record_i_64_string(dynamic raw);

  @protected
  (Uint8List, String, PlatformInt64)
  dco_decode_record_list_prim_u_8_strict_string_i_64(dynamic raw);

  @protected
  ShareResultDto dco_decode_share_result_dto(dynamic raw);

  @protected
  SourceFileMetaDto dco_decode_source_file_meta_dto(dynamic raw);

  @protected
  TimelineGroupDto dco_decode_timeline_group_dto(dynamic raw);

  @protected
  TrendPointDto dco_decode_trend_point_dto(dynamic raw);

  @protected
  TrendSeriesDto dco_decode_trend_series_dto(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VisitLabDto dco_decode_visit_lab_dto(dynamic raw);

  @protected
  VisitRecordDto dco_decode_visit_record_dto(dynamic raw);

  @protected
  VisitSummaryDto dco_decode_visit_summary_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActiveMedDto sse_decode_active_med_dto(SseDeserializer deserializer);

  @protected
  AllergyItemDto sse_decode_allergy_item_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ConsentDto sse_decode_box_autoadd_consent_dto(SseDeserializer deserializer);

  @protected
  DocumentSummaryDto sse_decode_box_autoadd_document_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  EncounterSummaryDto sse_decode_box_autoadd_encounter_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ChronicConditionDto sse_decode_chronic_condition_dto(
    SseDeserializer deserializer,
  );

  @protected
  ClaimResultDto sse_decode_claim_result_dto(SseDeserializer deserializer);

  @protected
  ConfirmedStatusDto sse_decode_confirmed_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConsentDto sse_decode_consent_dto(SseDeserializer deserializer);

  @protected
  DocumentDetailDto sse_decode_document_detail_dto(
    SseDeserializer deserializer,
  );

  @protected
  DocumentSummaryDto sse_decode_document_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  EmergencyCardDto sse_decode_emergency_card_dto(SseDeserializer deserializer);

  @protected
  EncounterSummaryDto sse_decode_encounter_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  ExportResultDto sse_decode_export_result_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IcloudStatusDto sse_decode_icloud_status_dto(SseDeserializer deserializer);

  @protected
  ImportOutcomeDto sse_decode_import_outcome_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ActiveMedDto> sse_decode_list_active_med_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AllergyItemDto> sse_decode_list_allergy_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ChronicConditionDto> sse_decode_list_chronic_condition_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ConfirmedStatusDto> sse_decode_list_confirmed_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DocumentSummaryDto> sse_decode_list_document_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProxyLabDto> sse_decode_list_proxy_lab_dto(SseDeserializer deserializer);

  @protected
  List<ProxyLabPointDto> sse_decode_list_proxy_lab_point_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ProxyMedDto> sse_decode_list_proxy_med_dto(SseDeserializer deserializer);

  @protected
  List<ProxyProblemDto> sse_decode_list_proxy_problem_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TimelineGroupDto> sse_decode_list_timeline_group_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TrendPointDto> sse_decode_list_trend_point_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TrendSeriesDto> sse_decode_list_trend_series_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<VisitLabDto> sse_decode_list_visit_lab_dto(SseDeserializer deserializer);

  @protected
  List<VisitRecordDto> sse_decode_list_visit_record_dto(
    SseDeserializer deserializer,
  );

  @protected
  OcrPpResultDto sse_decode_ocr_pp_result_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  PatientProfileDto sse_decode_patient_profile_dto(
    SseDeserializer deserializer,
  );

  @protected
  ProxyLabDto sse_decode_proxy_lab_dto(SseDeserializer deserializer);

  @protected
  ProxyLabPointDto sse_decode_proxy_lab_point_dto(SseDeserializer deserializer);

  @protected
  ProxyMedDto sse_decode_proxy_med_dto(SseDeserializer deserializer);

  @protected
  ProxyProblemDto sse_decode_proxy_problem_dto(SseDeserializer deserializer);

  @protected
  ProxySummaryDto sse_decode_proxy_summary_dto(SseDeserializer deserializer);

  @protected
  QrShareDto sse_decode_qr_share_dto(SseDeserializer deserializer);

  @protected
  (PlatformInt64, String) sse_decode_record_i_64_string(
    SseDeserializer deserializer,
  );

  @protected
  (Uint8List, String, PlatformInt64)
  sse_decode_record_list_prim_u_8_strict_string_i_64(
    SseDeserializer deserializer,
  );

  @protected
  ShareResultDto sse_decode_share_result_dto(SseDeserializer deserializer);

  @protected
  SourceFileMetaDto sse_decode_source_file_meta_dto(
    SseDeserializer deserializer,
  );

  @protected
  TimelineGroupDto sse_decode_timeline_group_dto(SseDeserializer deserializer);

  @protected
  TrendPointDto sse_decode_trend_point_dto(SseDeserializer deserializer);

  @protected
  TrendSeriesDto sse_decode_trend_series_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VisitLabDto sse_decode_visit_lab_dto(SseDeserializer deserializer);

  @protected
  VisitRecordDto sse_decode_visit_record_dto(SseDeserializer deserializer);

  @protected
  VisitSummaryDto sse_decode_visit_summary_dto(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_active_med_dto(ActiveMedDto self, SseSerializer serializer);

  @protected
  void sse_encode_allergy_item_dto(
    AllergyItemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_consent_dto(
    ConsentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_document_summary_dto(
    DocumentSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_encounter_summary_dto(
    EncounterSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chronic_condition_dto(
    ChronicConditionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_claim_result_dto(
    ClaimResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_confirmed_status_dto(
    ConfirmedStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_consent_dto(ConsentDto self, SseSerializer serializer);

  @protected
  void sse_encode_document_detail_dto(
    DocumentDetailDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_document_summary_dto(
    DocumentSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_emergency_card_dto(
    EmergencyCardDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_encounter_summary_dto(
    EncounterSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_result_dto(
    ExportResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_icloud_status_dto(
    IcloudStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_import_outcome_dto(
    ImportOutcomeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_active_med_dto(
    List<ActiveMedDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_allergy_item_dto(
    List<AllergyItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chronic_condition_dto(
    List<ChronicConditionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_confirmed_status_dto(
    List<ConfirmedStatusDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_document_summary_dto(
    List<DocumentSummaryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_lab_dto(
    List<ProxyLabDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_lab_point_dto(
    List<ProxyLabPointDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_med_dto(
    List<ProxyMedDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proxy_problem_dto(
    List<ProxyProblemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_timeline_group_dto(
    List<TimelineGroupDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trend_point_dto(
    List<TrendPointDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_trend_series_dto(
    List<TrendSeriesDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_visit_lab_dto(
    List<VisitLabDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_visit_record_dto(
    List<VisitRecordDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ocr_pp_result_dto(
    OcrPpResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_patient_profile_dto(
    PatientProfileDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_lab_dto(ProxyLabDto self, SseSerializer serializer);

  @protected
  void sse_encode_proxy_lab_point_dto(
    ProxyLabPointDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_med_dto(ProxyMedDto self, SseSerializer serializer);

  @protected
  void sse_encode_proxy_problem_dto(
    ProxyProblemDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proxy_summary_dto(
    ProxySummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qr_share_dto(QrShareDto self, SseSerializer serializer);

  @protected
  void sse_encode_record_i_64_string(
    (PlatformInt64, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_list_prim_u_8_strict_string_i_64(
    (Uint8List, String, PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_share_result_dto(
    ShareResultDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_file_meta_dto(
    SourceFileMetaDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timeline_group_dto(
    TimelineGroupDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_trend_point_dto(TrendPointDto self, SseSerializer serializer);

  @protected
  void sse_encode_trend_series_dto(
    TrendSeriesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_visit_lab_dto(VisitLabDto self, SseSerializer serializer);

  @protected
  void sse_encode_visit_record_dto(
    VisitRecordDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_visit_summary_dto(
    VisitSummaryDto self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
