// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dto.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_encounter`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// 认领结果:医生代拍的包被还原进本机保险箱之后,各类记录各有几份。
///
/// `deduped` 不是错误 —— 病人重复点同一条认领链接是常事,内容哈希会挡住,
/// UI 该说「已经在你的档案里了」而不是报错。`text_only` 则要如实告诉用户:
/// 这几份只还原了文字,原件没跟过来。
class ClaimResultDto {
  final PlatformInt64 imported;
  final PlatformInt64 deduped;
  final PlatformInt64 textOnly;

  const ClaimResultDto({
    required this.imported,
    required this.deduped,
    required this.textOnly,
  });

  @override
  int get hashCode => imported.hashCode ^ deduped.hashCode ^ textOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClaimResultDto &&
          runtimeType == other.runtimeType &&
          imported == other.imported &&
          deduped == other.deduped &&
          textOnly == other.textOnly;
}

/// 一份文档当前的「已确认」状态(医生代拍待确认列表)。**不**塞进共享的
/// `DocumentSummaryDto`(`vault.rs` 的正常病人档案列表也用它,这个状态只对医生
/// 代拍流程有意义)——待确认列表屏用 `document_id` 把这份状态与
/// `ephemeral_load_preview` 返回的文档列表在 Dart 侧做本地映射。由
/// `api::vault_ephemeral::ephemeral_confirmed_map` 产出。
class ConfirmedStatusDto {
  final PlatformInt64 documentId;
  final bool confirmed;

  const ConfirmedStatusDto({required this.documentId, required this.confirmed});

  @override
  int get hashCode => documentId.hashCode ^ confirmed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfirmedStatusDto &&
          runtimeType == other.runtimeType &&
          documentId == other.documentId &&
          confirmed == other.confirmed;
}

/// 拍前同意记录(医生代拍病人纸质材料流程):病人同意的方式(手写签名 / 按住
/// 确认)、时刻、文案版本。由 `screens/doctor/consent_screen.dart` 产出,经
/// `api::vault_ephemeral::ephemeral_create_share` 转换成
/// `medme_share::share::ShareConsent` 塞进加密分享包(见该函数的 `From` 实现)。
class ConsentDto {
  /// 同意时刻(UTC RFC3339)。
  final String utcTs;

  /// 同意告知文案的版本号(见 `consent_screen.dart` 的 `kConsentTextVersion`)。
  final String consentTextVersion;

  /// 手写签名 PNG 的 base64;按住确认(无签名图像)时为 `None`。
  final String? signaturePngBase64;

  /// "signature" | "press_hold"。
  final String method;

  /// 本次临时会话的人类可读标识,供医生/病人事后核对「哪一次代建档」
  /// (不是安全边界——临时会话的一次性随机 device_id 才是,见 `vault_ephemeral.rs`)。
  final String sessionId;

  const ConsentDto({
    required this.utcTs,
    required this.consentTextVersion,
    this.signaturePngBase64,
    required this.method,
    required this.sessionId,
  });

  @override
  int get hashCode =>
      utcTs.hashCode ^
      consentTextVersion.hashCode ^
      signaturePngBase64.hashCode ^
      method.hashCode ^
      sessionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConsentDto &&
          runtimeType == other.runtimeType &&
          utcTs == other.utcTs &&
          consentTextVersion == other.consentTextVersion &&
          signaturePngBase64 == other.signaturePngBase64 &&
          method == other.method &&
          sessionId == other.sessionId;
}

/// 「载入示例数据」的进度回报(`api::vault::load_demo_data` 经 `StreamSink` 逐份
/// 推给 Dart)。真机实测过全程 11 秒零反馈——不是慢,是安卓那次 22 份的循环里
/// Dart 侧原来只等一个 `Future`,中途没有任何信号可渲染。这里补一个流,让设置屏
/// 能画「正在载入 N/total」而不是一个不知道在不在跑的忙态。
///
/// **`error` 而不是让整个函数返回 `Err`**:FRB 里带 `StreamSink` 参数的函数,
/// Dart 侧签名会整个折成 `Stream<T>`——函数自身的 `Result` 只用来标记这一次
/// FFI 调用本身,`load_demo_data` 内部通过 `unawaited(...)` 发起,没有代码
/// `await` 它,一旦真返回 `Err` 就是一次悄悄丢失、连 Dart 的 `try/catch` 都接不住
/// 的异常(本工单要修的正是「失败静默不可见」,不能在同一次改动里换个地方复发)。
/// 所以 `load_demo_data` 恒返回 `Ok(())`,任何失败(保险箱未打开、磁盘写入失败等)
/// 都经这个 `error` 字段随流报出来,Dart 侧照常能 `catch`。
class DemoLoadProgressDto {
  /// 已处理(尝试过,含失败)的份数;发生 `error` 时为 0。
  final PlatformInt64 loaded;

  /// 总份数;发生 `error` 时为 0(还没来得及数出总数就失败了)。
  final PlatformInt64 total;

  /// 到目前为止成功入库的份数(累计)。
  final PlatformInt64 succeeded;

  /// 整个操作失败的原因;正常进行中/正常完成为 `None`。
  final String? error;

  const DemoLoadProgressDto({
    required this.loaded,
    required this.total,
    required this.succeeded,
    this.error,
  });

  @override
  int get hashCode =>
      loaded.hashCode ^ total.hashCode ^ succeeded.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DemoLoadProgressDto &&
          runtimeType == other.runtimeType &&
          loaded == other.loaded &&
          total == other.total &&
          succeeded == other.succeeded &&
          error == other.error;
}

/// 文档详情:类型/日期(在 document 里)+ 来源文件 + 识别文本 + 还缺哪几页。
class DocumentDetailDto {
  final DocumentSummaryDto document;
  final SourceFileMetaDto sourceFile;
  final String ocrText;
  final double? ocrConfidence;
  final String? ocrBackend;

  /// 这份文档里**至今没有任何识别文字**的页码(1-based,升序)。
  ///
  /// 为什么详情页需要这个:漏页这件事此前**只在导入那一刻的结果框里说过一次**
  /// ——「已识别入库,但 3 页未能识别文字」。那个框一关,信息就永远消失了:
  /// 详情页不显示、档案列表不显示,用户过一周再打开这份文档,看到的是一份
  /// 「正常」的病历,而里面有 3 页是空的。他不会知道要去补,也不会知道医生
  /// 看到的摘要少了那几页的内容。
  ///
  /// 现查现算(`page_count` 减去 `ocr_result` 里已有的页),不是把导入时的
  /// 结论存下来 —— 因为那个结论会过期:#193 之后「再导一次同一份文件」会补页,
  /// 端上的按页回填也会补页,存下来的旧值只会骗人。
  final Int32List pagesWithoutText;

  const DocumentDetailDto({
    required this.document,
    required this.sourceFile,
    required this.ocrText,
    this.ocrConfidence,
    this.ocrBackend,
    required this.pagesWithoutText,
  });

  @override
  int get hashCode =>
      document.hashCode ^
      sourceFile.hashCode ^
      ocrText.hashCode ^
      ocrConfidence.hashCode ^
      ocrBackend.hashCode ^
      pagesWithoutText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentDetailDto &&
          runtimeType == other.runtimeType &&
          document == other.document &&
          sourceFile == other.sourceFile &&
          ocrText == other.ocrText &&
          ocrConfidence == other.ocrConfidence &&
          ocrBackend == other.ocrBackend &&
          pagesWithoutText == other.pagesWithoutText;
}

class DocumentSummaryDto {
  final PlatformInt64 id;
  final String docType;
  final String? docDate;
  final String? docDateEnd;
  final String? title;
  final int pageCount;

  /// 影像检查文档的切片数;非影像文档为 None。
  final int? sliceCount;

  const DocumentSummaryDto({
    required this.id,
    required this.docType,
    this.docDate,
    this.docDateEnd,
    this.title,
    required this.pageCount,
    this.sliceCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      docType.hashCode ^
      docDate.hashCode ^
      docDateEnd.hashCode ^
      title.hashCode ^
      pageCount.hashCode ^
      sliceCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          docType == other.docType &&
          docDate == other.docDate &&
          docDateEnd == other.docDateEnd &&
          title == other.title &&
          pageCount == other.pageCount &&
          sliceCount == other.sliceCount;
}

class EncounterSummaryDto {
  final PlatformInt64 id;
  final String kind;
  final String? provider;
  final String? startDate;
  final String? endDate;
  final String? title;
  final bool transferred;
  final PlatformInt64 docCount;

  const EncounterSummaryDto({
    required this.id,
    required this.kind,
    this.provider,
    this.startDate,
    this.endDate,
    this.title,
    required this.transferred,
    required this.docCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      provider.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      title.hashCode ^
      transferred.hashCode ^
      docCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncounterSummaryDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          provider == other.provider &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          title == other.title &&
          transferred == other.transferred &&
          docCount == other.docCount;
}

/// 时间线导出结果:未加密、可打印的自包含 HTML。与 `ShareResultDto` 不同,
/// 没有口令——导出内容不加密,靠系统「分享」sheet 直接交给医生 / 存下来打印。
class ExportResultDto {
  final PlatformInt64 recordCount;
  final PlatformInt64 byteSize;
  final String path;

  const ExportResultDto({
    required this.recordCount,
    required this.byteSize,
    required this.path,
  });

  @override
  int get hashCode => recordCount.hashCode ^ byteSize.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportResultDto &&
          runtimeType == other.runtimeType &&
          recordCount == other.recordCount &&
          byteSize == other.byteSize &&
          path == other.path;
}

/// iCloud 同步状态(设置页开关据此渲染)。`available` = 当前能否解析到 iCloud
/// 容器(iOS-only,由 Dart 侧经 `medme/icloud` MethodChannel 判断后覆盖;Rust
/// 恒返回 false);`enabled` = 本设备是否已开启同步(Rust 据持久标记返回)。
/// 开关/迁移逻辑见 `api::vault` 的 `enable_icloud_sync` / `disable_icloud_sync`。
class IcloudStatusDto {
  final bool available;
  final bool enabled;

  const IcloudStatusDto({required this.available, required this.enabled});

  @override
  int get hashCode => available.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IcloudStatusDto &&
          runtimeType == other.runtimeType &&
          available == other.available &&
          enabled == other.enabled;
}

class ImportOutcomeDto {
  final String name;
  final PlatformInt64 sourceFileId;
  final String status;
  final String? docType;

  /// 本次采集落库的文档 id(前端「待确认」review 队列据此显式标记新导入)。
  /// 去重/失败等没建文档的情况为 None。
  final PlatformInt64? documentId;

  /// 从本份报告文本里识别出的**患者姓名**(`parser::extract_demographics`)。
  /// 前端用它和当前成员档案名字比对——不一致就在「待确认」里标红警告(防导错人)。
  /// 识别不到为 None。
  final String? detectedName;

  /// PDF 专属(其他文件类型恒为空):1-based 页码,列出既没有文本层、也没能
  /// 在落库时 OCR 出文字的页(移动端未链接 Rust OCR 引擎,这里几乎总是非空的
  /// "待处理"清单)。前端**必须**据此显式提示用户,不能让人以为整份 PDF 都
  /// 识别完了——这正是"混合页 PDF 静默丢数据"缺陷的修复点(见
  /// `pipeline::ingest_pdf` 文档注释)。`import_flow.dart` 用它驱动逐页 OCR
  /// 回填(`backfillPdfText`),回填后仍剩的页数进导入汇总弹窗。
  final Int32List pagesWithoutText;

  const ImportOutcomeDto({
    required this.name,
    required this.sourceFileId,
    required this.status,
    this.docType,
    this.documentId,
    this.detectedName,
    required this.pagesWithoutText,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      sourceFileId.hashCode ^
      status.hashCode ^
      docType.hashCode ^
      documentId.hashCode ^
      detectedName.hashCode ^
      pagesWithoutText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportOutcomeDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          sourceFileId == other.sourceFileId &&
          status == other.status &&
          docType == other.docType &&
          documentId == other.documentId &&
          detectedName == other.detectedName &&
          pagesWithoutText == other.pagesWithoutText;
}

/// **iOS PP-OCRv5 测试路径**结果(feat/ios-pp-ocr-test 分支,探索性——ADR 0005
/// 尚未 supersede)。镜像 Dart `OcrResult`(`ocr_bridge.dart`),供
/// `recognize_image_pp` 返回,让真机能对比 Apple Vision vs PP-OCRv5 的识别质量。
class OcrPpResultDto {
  final String text;
  final double confidence;

  const OcrPpResultDto({required this.text, required this.confidence});

  @override
  int get hashCode => text.hashCode ^ confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrPpResultDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          confidence == other.confidence;
}

class PatientProfileDto {
  final String? name;
  final String? gender;
  final String? birthDate;
  final String? age;
  final PlatformInt64 recordCount;

  const PatientProfileDto({
    this.name,
    this.gender,
    this.birthDate,
    this.age,
    required this.recordCount,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      gender.hashCode ^
      birthDate.hashCode ^
      age.hashCode ^
      recordCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PatientProfileDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          gender == other.gender &&
          birthDate == other.birthDate &&
          age == other.age &&
          recordCount == other.recordCount;
}

/// `api::vault::ingest_bytes_with_progress` 经 `StreamSink` 逐页推给 Dart 的
/// 扫描版 PDF OCR 进度,配合 `import_flow.dart` 画「正在识别第 N/M 页」。
///
/// **为什么这条路会被卡住几十秒零反馈**:测试 PDF 的扫描页几乎全是 JPEG
/// (DCTDecode)编码——手机拍照 / App 导出扫描件最常见的编码——而
/// `packages/ocr` 的 `recognize_pdf_mixed` 自己就能 OCR 这种页
/// (`extract_dct_images`)。于是耗时全砸在 `ingest_bytes` 这一次 Rust 调用
/// 里,`import_flow.dart` 里那条按页回填的进度(`onPage` 回调,只在 Rust
/// 没能处理时才触发)一次都没机会跑——真机上一份 25 页的扫描件是几十秒量级,
/// 屏幕上却什么进度都没有。这个 DTO 就是给这几十秒补一个进度出口。
///
/// **`outcome`/`error` 而不是让函数自身返回值——同 [DemoLoadProgressDto]
/// 顶部那段坑**:带 `StreamSink` 参数的 FRB 函数,Dart 侧签名整个折成
/// `Stream<T>`,没有任何代码 `await` 函数自身的 `Result`。旧版 `ingest_bytes`
/// 靠返回值报成败——如果 `ingest_bytes_with_progress` 也这样处理,恒返回
/// `Ok(())` 却不把结果塞进流,就是把「导入失败」原样静默成功,和这张工单要
/// 修的缺陷是同一个坑换个地方复发。所以每次调用的终态都在流的**最后一条**
/// 消息里,`outcome`(成功)与 `error`(失败)二者恰好其一非 `None`;中间的
/// 进度消息两者都是 `None`。
class PdfImportProgressDto {
  /// 已识别完的页码(1-based)。终态消息(`outcome`/`error` 非 `None`)固定
  /// 为 0——彼时页进度已经没有意义。
  final int page;

  /// 这份 PDF 的真实总页数。终态消息固定为 0。
  final int total;

  /// 导入成功的终态结果;仅在流的最后一条消息里非 `None`,与 `error` 互斥。
  final ImportOutcomeDto? outcome;

  /// 导入失败的原因;仅在流的最后一条消息里非 `None`,与 `outcome` 互斥。
  final String? error;

  const PdfImportProgressDto({
    required this.page,
    required this.total,
    this.outcome,
    this.error,
  });

  @override
  int get hashCode =>
      page.hashCode ^ total.hashCode ^ outcome.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PdfImportProgressDto &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          total == other.total &&
          outcome == other.outcome &&
          error == other.error;
}

/// 一条化验序列:最近值 + 趋势 + 最近几个点(≤4,时间升序)。没有任何带日期的点
/// (`assemble_summary` 的 `pts` 只保留带日期的观测)时不产出——审阅屏没法从中读出
/// 「最近值」,原始识别文字仍在下方「逐份识别内容」区块里,不丢信息。
class ProxyLabDto {
  final String name;
  final String? unit;
  final double latestValue;
  final double? refHigh;
  final double? refLow;

  /// "up" | "down" | "flat" | "single"(只有一个带日期的点,不足以判断趋势)。
  final String trend;
  final List<ProxyLabPointDto> recentPoints;

  const ProxyLabDto({
    required this.name,
    this.unit,
    required this.latestValue,
    this.refHigh,
    this.refLow,
    required this.trend,
    required this.recentPoints,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      unit.hashCode ^
      latestValue.hashCode ^
      refHigh.hashCode ^
      refLow.hashCode ^
      trend.hashCode ^
      recentPoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyLabDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          unit == other.unit &&
          latestValue == other.latestValue &&
          refHigh == other.refHigh &&
          refLow == other.refLow &&
          trend == other.trend &&
          recentPoints == other.recentPoints;
}

class ProxyLabPointDto {
  /// "YYYY-MM"。
  final String month;
  final double value;

  const ProxyLabPointDto({required this.month, required this.value});

  @override
  int get hashCode => month.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyLabPointDto &&
          runtimeType == other.runtimeType &&
          month == other.month &&
          value == other.value;
}

/// 一条在用药:名 + 最近一次提到的剂量(若识别到)+ 是否在用。字段名 `active`
/// 而不是 `assemble_summary` json 里的 `on`——后者是 Dart 的保留字上下文关键字,
/// FRB codegen 会把它改名成 `on_`,不如从 Rust 侧就用一个干净的名字。
class ProxyMedDto {
  final String name;
  final String? dose;
  final bool active;

  const ProxyMedDto({required this.name, this.dose, required this.active});

  @override
  int get hashCode => name.hashCode ^ dose.hashCode ^ active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyMedDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          dose == other.dose &&
          active == other.active;
}

/// 一条在治问题:名字 + 状态,嵌套它的关键化验与在用药。
class ProxyProblemDto {
  final String term;

  /// "在管" | "需关注" | "其他"(未挂上具体疾病的化验/用药落这个桶,见
  /// `parser::handoff::assemble_summary` 的「其他」bucket)。
  final String status;
  final bool warn;
  final List<ProxyLabDto> labs;
  final List<ProxyMedDto> meds;

  const ProxyProblemDto({
    required this.term,
    required this.status,
    required this.warn,
    required this.labs,
    required this.meds,
  });

  @override
  int get hashCode =>
      term.hashCode ^
      status.hashCode ^
      warn.hashCode ^
      labs.hashCode ^
      meds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxyProblemDto &&
          runtimeType == other.runtimeType &&
          term == other.term &&
          status == other.status &&
          warn == other.warn &&
          labs == other.labs &&
          meds == other.meds;
}

/// 「病情摘要卡」(医生代拍审阅屏,选项 b):在治的病 + 关键化验 + 在用药,
/// 三十秒看懂大局。由 `api::vault_ephemeral::ephemeral_summary` 产出——把
/// `parser::assemble_summary` 的通用 `serde_json::Value`(查看器/加密分享用的同一份
/// 装配逻辑)映射成 FRB 能直接生成 Dart 绑定的定型结构。**不做 QR 分享那种带宽裁剪**
/// (`medme_share::qr::trim_summary` 的 `max_problems`/`active_meds_only` 等是为
/// 二维码容量服务的,审阅屏要的是「拍了什么就看到什么」的完整核对,不是带宽约束)——
/// 唯一的裁剪是每条化验只保留最近 4 个点,与 `notable_changes`/QR 默认档同一惯例
/// (给「趋势一眼」用,不是画完整图表)。
class ProxySummaryDto {
  final List<ProxyProblemDto> problems;

  const ProxySummaryDto({required this.problems});

  @override
  int get hashCode => problems.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProxySummaryDto &&
          runtimeType == other.runtimeType &&
          problems == other.problems;
}

/// 二维码分享结果:一条可直接编码成二维码的 URL、带上的疾病数、以及是否仍在
/// 二维码容量内(按构造裁剪后应恒为 true,留作兜底提示)。
class QrShareDto {
  final String url;
  final PlatformInt64 problemCount;
  final bool fitsQr;

  const QrShareDto({
    required this.url,
    required this.problemCount,
    required this.fitsQr,
  });

  @override
  int get hashCode => url.hashCode ^ problemCount.hashCode ^ fitsQr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QrShareDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          problemCount == other.problemCount &&
          fitsQr == other.fitsQr;
}

/// 一次「记录」(手动录入)里的一个数值 —— 血压一次记录有两个(收缩压+舒张压,
/// 共享同一份文档/`measuredAt`,见 `add_self_measurement` 的文档),其余四项各
/// 一个。`analyteKey`/`unit` 都是 `terminology` 词典里现成的规范键/单位
/// (`bp_systolic`/`bp_diastolic`/`heart_rate`/`body_weight`/`body_temperature`/
/// `glucose`,单位分别是 mmHg/mmHg/`/min`/kg/Cel/mmol/L)——Dart 侧只从封闭的
/// 五选一录入界面产出这个结构,不接受任意字符串(硬约束:不做手打化验值)。
/// 与 `parser::SelfMeasuredValue` 逐字段镜像,只是换成 FRB 能生成绑定的 plain
/// struct(见本文件头的取舍)。
class SelfMeasuredValueDto {
  final String analyteKey;
  final double value;
  final String unit;

  const SelfMeasuredValueDto({
    required this.analyteKey,
    required this.value,
    required this.unit,
  });

  @override
  int get hashCode => analyteKey.hashCode ^ value.hashCode ^ unit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SelfMeasuredValueDto &&
          runtimeType == other.runtimeType &&
          analyteKey == other.analyteKey &&
          value == other.value &&
          unit == other.unit;
}

/// 加密分享生成结果:口令(单独告知医生)、记录数、文件字节数、分享文件路径。
class ShareResultDto {
  final String passphrase;
  final PlatformInt64 recordCount;
  final PlatformInt64 byteSize;
  final String path;

  const ShareResultDto({
    required this.passphrase,
    required this.recordCount,
    required this.byteSize,
    required this.path,
  });

  @override
  int get hashCode =>
      passphrase.hashCode ^
      recordCount.hashCode ^
      byteSize.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareResultDto &&
          runtimeType == other.runtimeType &&
          passphrase == other.passphrase &&
          recordCount == other.recordCount &&
          byteSize == other.byteSize &&
          path == other.path;
}

/// 原始文件元信息(文档详情页展示来源 + 前端据此判断是否为图片以渲染缩略)。
class SourceFileMetaDto {
  final PlatformInt64 id;
  final String originalName;
  final String mimeType;
  final PlatformInt64 byteSize;
  final String importedAt;

  const SourceFileMetaDto({
    required this.id,
    required this.originalName,
    required this.mimeType,
    required this.byteSize,
    required this.importedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      originalName.hashCode ^
      mimeType.hashCode ^
      byteSize.hashCode ^
      importedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceFileMetaDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          originalName == other.originalName &&
          mimeType == other.mimeType &&
          byteSize == other.byteSize &&
          importedAt == other.importedAt;
}

@freezed
sealed class TimelineGroupDto with _$TimelineGroupDto {
  const TimelineGroupDto._();

  const factory TimelineGroupDto.encounter({
    required EncounterSummaryDto encounter,
    required List<DocumentSummaryDto> docs,
  }) = TimelineGroupDto_Encounter;
  const factory TimelineGroupDto.document({required DocumentSummaryDto doc}) =
      TimelineGroupDto_Document;
}
