// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key32`

Future<(Uint8List, Uint8List)> syncAccountKeysNew() =>
    RustLib.instance.api.crateApiVaultSyncSyncAccountKeysNew();

Future<Uint8List> syncWrapPrivate({
  required List<int> secret,
  required String password,
  required List<int> salt,
  required int mKib,
  required int t,
  required int p,
}) => RustLib.instance.api.crateApiVaultSyncSyncWrapPrivate(
  secret: secret,
  password: password,
  salt: salt,
  mKib: mKib,
  t: t,
  p: p,
);

Future<Uint8List> syncUnwrapPrivatePw({
  required List<int> blob,
  required String password,
  required List<int> salt,
  required int mKib,
  required int t,
  required int p,
}) => RustLib.instance.api.crateApiVaultSyncSyncUnwrapPrivatePw(
  blob: blob,
  password: password,
  salt: salt,
  mKib: mKib,
  t: t,
  p: p,
);

Future<String> syncRecoveryCodeNew() =>
    RustLib.instance.api.crateApiVaultSyncSyncRecoveryCodeNew();

Future<Uint8List> syncWrapPrivateRc({
  required List<int> secret,
  required String code,
}) => RustLib.instance.api.crateApiVaultSyncSyncWrapPrivateRc(
  secret: secret,
  code: code,
);

Future<Uint8List> syncUnwrapPrivateRc({
  required List<int> blob,
  required String code,
}) => RustLib.instance.api.crateApiVaultSyncSyncUnwrapPrivateRc(
  blob: blob,
  code: code,
);

/// 邀请场景:`kek = HKDF(token)`(见 `sync::kek_from_token`,salt
/// `medme-invite-v1`,与口令/恢复码的 `account-priv-v1` AAD 分开用 `invite-v1`)。
Future<Uint8List> syncWrapWithToken({
  required List<int> plaintext,
  required String token,
}) => RustLib.instance.api.crateApiVaultSyncSyncWrapWithToken(
  plaintext: plaintext,
  token: token,
);

Future<Uint8List> syncUnwrapWithToken({
  required List<int> blob,
  required String token,
}) => RustLib.instance.api.crateApiVaultSyncSyncUnwrapWithToken(
  blob: blob,
  token: token,
);

Future<Uint8List> syncProfileKeyNew() =>
    RustLib.instance.api.crateApiVaultSyncSyncProfileKeyNew();

Future<Uint8List> syncSealTo({
  required List<int> public,
  required List<int> plaintext,
}) => RustLib.instance.api.crateApiVaultSyncSyncSealTo(
  public: public,
  plaintext: plaintext,
);

Future<Uint8List> syncOpenSealed({
  required List<int> secret,
  required List<int> blob,
}) => RustLib.instance.api.crateApiVaultSyncSyncOpenSealed(
  secret: secret,
  blob: blob,
);

/// 与 `open_vault` 同布局(`<docs_dir>/vault` 真相 + `<data_dir>` 本机设备
/// id),但用档案密钥 keyed 打开(`Vault::open_split_resilient_with_key`),
/// 且不走 iCloud——云账号同步是另一条同步路径,两者不共用 iCloud 容器解析。
Future<void> syncOpenProfileVault({
  required String docsDir,
  required String dataDir,
  required List<int> profileKey,
}) => RustLib.instance.api.crateApiVaultSyncSyncOpenProfileVault(
  docsDir: docsDir,
  dataDir: dataDir,
  profileKey: profileKey,
);

/// 本机每个 device 段当前**可信**的最大 seq(见
/// `core_model::sync_io::device_seq_map` 文档:被隔离的条目不计入)。推送前
/// 拿这个当"服务端已有到哪"的起点,拉取前当"本机已有到哪"的水位。
Future<List<(String, PlatformInt64)>> syncLocalSeqMap() =>
    RustLib.instance.api.crateApiVaultSyncSyncLocalSeqMap();

/// 导出本机日志里 `seq > after[device_id]`(未提供该 device 则视为 0)的条目,
/// 逐条整体加密(AAD = `event_id`,防止信封字段与密文错配后被悄悄接受)。
Future<List<SyncEventDto>> syncExportEvents({
  required List<int> profileKey,
  required List<(String, PlatformInt64)> after,
}) => RustLib.instance.api.crateApiVaultSyncSyncExportEvents(
  profileKey: profileKey,
  after: after,
);

/// 解密 + 校验信封字段与解密出的条目一致(拒收错配),交给
/// `append_peer_entries` 按 `(device_id, seq)` 去重/校验链/MAC 落盘。
Future<SyncImportOutcomeDto> syncImportEvents({
  required List<int> profileKey,
  required List<SyncEventDto> events,
}) => RustLib.instance.api.crateApiVaultSyncSyncImportEvents(
  profileKey: profileKey,
  events: events,
);

/// 事件引用了、但本机 `objects/` 里还没有的对象——按 `object_id`(服务端可见的
/// 别名,内容哈希经档案密钥 HMAC)列出待拉清单。
Future<List<(String, String)>> syncMissingObjects({
  required List<int> profileKey,
}) => RustLib.instance.api.crateApiVaultSyncSyncMissingObjects(
  profileKey: profileKey,
);

/// 本机日志引用、且已在 CAS 落地的对象全量清单(推送用)——同一批哈希来源与
/// `missing_object_hashes` 一致,只是反过来只留「本地已有」的。
Future<List<(String, String)>> syncAllObjectIds({
  required List<int> profileKey,
}) => RustLib.instance.api.crateApiVaultSyncSyncAllObjectIds(
  profileKey: profileKey,
);

/// 读本地 CAS 对象 + 加密(AAD = `object_id`)供上传;`object_id` 一并带回,
/// 调用方(Dart)不需要在本地重算一遍。
Future<(String, Uint8List)> syncEncryptObject({
  required List<int> profileKey,
  required String hash,
}) => RustLib.instance.api.crateApiVaultSyncSyncEncryptObject(
  profileKey: profileKey,
  hash: hash,
);

/// 解密拉回来的对象、存入本地 CAS,并校验解密出的明文哈希经档案密钥算出的
/// `object_id` 与传入的 `object_id` 一致(内容与其服务端别名对不上就丢弃,
/// 不落库)。`store_object` 已存在则不重写(见其文档:已存在的对象跳过写入),
/// 但这条校验仍然执行。写完后 `materialize` 一次,让新对象覆盖到的文档立刻
/// 可见(单独对象拉取的调用方——即本函数——负责这一步)。
Future<String> syncStoreObject({
  required List<int> profileKey,
  required String objectId,
  required List<int> ciphertext,
}) => RustLib.instance.api.crateApiVaultSyncSyncStoreObject(
  profileKey: profileKey,
  objectId: objectId,
  ciphertext: ciphertext,
);

Future<int> syncDateShiftDays({required List<int> profileKey}) => RustLib
    .instance
    .api
    .crateApiVaultSyncSyncDateShiftDays(profileKey: profileKey);

/// Argon2id KDF 真机基准(设置页/首次建号按结果调参数,不写死 `KDF_DEFAULT`)。
Future<BigInt> syncKdfBenchMs({
  required int mKib,
  required int t,
  required int p,
}) => RustLib.instance.api.crateApiVaultSyncSyncKdfBenchMs(
  mKib: mKib,
  t: t,
  p: p,
);
