// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `alias_only_entry`, `analyte_entry`, `human_lines`, `installed_packages`, `kind_label`, `overlay_entries`, `today`

/// 验清单的签名并原样交给 Dart。**Dart 永远不自己解析未验签的清单** —— 那是中间人
/// 改一行 `version` 就能拿去拼路径的地方(`lib/skill_packages.dart`)。
Future<String> vaultProfileVerifyIndex({required String envelopeJson}) =>
    RustLib.instance.api.crateApiVaultProfileVaultProfileVerifyIndex(
      envelopeJson: envelopeJson,
    );

/// 装包,返回包 id。验签、引擎版本闸、单调版本闸(拒绝降级)全在
/// `profile::cache_store` 里,这里只把它的错误原样变成 Dart 读得到的一句话,**不吞**。
Future<String> vaultProfileInstallPackage({
  required String dir,
  required String envelopeJson,
}) => RustLib.instance.api.crateApiVaultProfileVaultProfileInstallPackage(
  dir: dir,
  envelopeJson: envelopeJson,
);

/// 算一份 `ProfileView` 并序列化给 Dart。**纯投影**:不写任何东西进保险箱。
///
/// `today` 取设备本地日期 —— 「今天该不该复查」是按用户所在时区的今天算的,
/// UTC 会让东八区的清晨算成昨天。
Future<String> vaultProfileView({
  required String dir,
  required String packageId,
}) => RustLib.instance.api.crateApiVaultProfileVaultProfileView(
  dir: dir,
  packageId: packageId,
);

/// 首页待办:所有**已开启**档案里到期的提醒(`never` / `overdue`)。整箱病历只读一次,
/// 每个包各算一遍 `materialize`;没开启的包一块都不算(spec §4)。`pending`(规则没
/// 核实)不进首页——那是档案页里「只显示不到期」的东西。
Future<String> vaultProfileDueReminders({required String dir}) =>
    RustLib.instance.api.crateApiVaultProfileVaultProfileDueReminders(dir: dir);

/// 按**当前开着的保险箱**重装术语覆盖层(装着且开着的包的 `terms` 合并成一份)。
///
/// 覆盖层是**进程级全局**,而保险箱是一次一个:换成员之后不重装,上一个成员开的
/// 病种词典还挂在全局词典上。所以换箱那一侧先清空(`vault::open_vault` /
/// `vault_sync::sync_open_profile_vault` 成功换箱后各清一次),由开完箱的调用方
/// (`lib/vault_boot.dart`)再调本函数按新箱子重装 —— 于是趋势页这些**不走病程
/// 档案**的界面,也能在开机后就认得包里的新分析物,而不必等用户先点开档案页。
///
/// 没开箱 / 读不到动作日志时报错(调用方按「这次没装上」处理即可,别让它挡住开箱)。
Future<void> vaultProfileRefreshTerms({required String dir}) =>
    RustLib.instance.api.crateApiVaultProfileVaultProfileRefreshTerms(dir: dir);

/// 记一条用户动作(开启/关闭某个病、确认诊断、记一次复发……),返回 document id。
///
/// 与 `add_note`/`add_self_measurement` **完全同一条路径**
/// (`vault::add_synthetic_document`):合成文本当"文件"过一遍 `import`,零新事件
/// 类型 —— 保险箱格式一个字节都不动,桌面照样读得懂、照样同步。
///
/// `at` 是**事件发生的那天**(用户说的那天,不是记录那天),必须是 `YYYY-MM-DD`:
/// 开关闸按它排序(`profile::is_enabled`),形状不对会悄悄排错,所以在这道边界上
/// 就挡住。`payload` 必须是 JSON **对象**:规则只按键取值,`null`/数组/裸数字对
/// 任何一条规则都只是噪音,别让它进日志。
///
/// **正文里必须有一行随记录时刻变的字节**(`记录时间:`,与自测记录同一手法,
/// `vault.rs` 的 `add_self_measurement_to`)。否则同 `(kind, package, at, payload)`
/// 的第二次记录会被 `Vault::import` 的 CAS 按**内容**去重,直接回传旧 document id、
/// 一条事件都不追加 —— 同一天「开→关→再开」就再也开不回来,而 FFI 还返回 `Ok`。
Future<PlatformInt64> vaultProfileRecordEvent({
  required String kind,
  required String package,
  required String at,
  required String payloadJson,
}) => RustLib.instance.api.crateApiVaultProfileVaultProfileRecordEvent(
  kind: kind,
  package: package,
  at: at,
  payloadJson: payloadJson,
);
