// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `alias_only_entry`, `analyte_entry`, `human_lines`, `installed_packages`, `kind_label`, `overlay_entries`, `today`

/// 验清单的签名并原样交给 Dart。**Dart 永远不自己解析未验签的清单** —— 那是中间人
/// 改一行 `version` 就能拿去拼路径的地方(`lib/skill_packages.dart`)。
Future<String> vaultProfileVerifyIndex({required String envelopeJson}) =>
    RustLib.instance.api.crateApiVaultProfileVaultProfileVerifyIndex(
      envelopeJson: envelopeJson,
    );

/// 装包,返回包 id。验签、引擎版本闸、单调版本闸(拒绝降级)全在
/// `profile::cache_store` 里,这里只把它的错误原样变成 Dart 读得到的一句话,**不吞**。
Future<String> vaultProfileInstallPackage({
  required String dir,
  required String envelopeJson,
}) => RustLib.instance.api.crateApiVaultProfileVaultProfileInstallPackage(
  dir: dir,
  envelopeJson: envelopeJson,
);

/// 算一份 `ProfileView` 并序列化给 Dart。**纯投影**:不写任何东西进保险箱。
///
/// `today` 取设备本地日期 —— 「今天该不该复查」是按用户所在时区的今天算的,
/// UTC 会让东八区的清晨算成昨天。
Future<String> vaultProfileView({
  required String dir,
  required String packageId,
}) => RustLib.instance.api.crateApiVaultProfileVaultProfileView(
  dir: dir,
  packageId: packageId,
);

/// 记一条用户动作(开启/关闭某个病、确认诊断、记一次复发……),返回 document id。
///
/// 与 `add_note`/`add_self_measurement` **完全同一条路径**
/// (`vault::add_synthetic_document`):合成文本当"文件"过一遍 `import`,零新事件
/// 类型 —— 保险箱格式一个字节都不动,桌面照样读得懂、照样同步。
///
/// `at` 是**事件发生的那天**(用户说的那天,不是记录那天),必须是 `YYYY-MM-DD`:
/// 开关闸按它排序(`profile::is_enabled`),形状不对会悄悄排错,所以在这道边界上
/// 就挡住。
///
/// 同一天、同一 kind、同一 payload 记两次会被 CAS 去重成**同一份文档**(字节逐字
/// 相同)。这不是 bug:`at` 只到天,两条一模一样的记录本来就分不出先后,而闸读的
/// 是「最新那条是什么」,结果一样。
Future<PlatformInt64> vaultProfileRecordEvent({
  required String kind,
  required String package,
  required String at,
  required String payloadJson,
}) => RustLib.instance.api.crateApiVaultProfileVaultProfileRecordEvent(
  kind: kind,
  package: package,
  at: at,
  payloadJson: payloadJson,
);
