// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_active_meds`, `collect_allergies`, `collect_conditions`, `collect_recent_notes`, `document_ids_for`, `extract_allergies_pairs`, `fmt_date`, `fmt_num`, `gather`, `is_renderable`, `parse_allergy_item`, `parse_rfc3339_date`, `render_plain_text`, `source_docs`, `trend_series`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProjectionDoc`, `VaultProjection`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 分组 chip 的完整目录,固定顺序(策展在 `terminology::PANEL_CATALOG`,与每条
/// [`TrendSeriesDto::panel`] 用的是同一份表)。**只回答「有哪些大类、先后顺序是
/// 什么」**——UI 不应该自己另定一份顺序(比如按"数据里第一次出现的顺序"排),
/// 否则两端顺序会漂移,同一个人重新打开页面 chip 顺序都可能不一样。
///
/// 不含「全部」「其他」—— 那两个是 UI 侧的兜底 sentinel,不是词典策展出来的大类,
/// 不该跟着这份表的「怎么算」走。
Future<List<String>> viewTrendPanelCatalog() =>
    RustLib.instance.api.crateApiVaultProjectionsViewTrendPanelCatalog();

/// **趋势图**:病人保险箱里每一条可渲染的化验序列,全保真。
///
/// 与「病情摘要卡」(`proxy_summary`)的区别见本文件头:这里不截断点数、保留日精度
/// 日期与每点的 H/L 标记、每点都带真实 document_id。
///
/// 序列顺序沿用 `parser::aggregate` 的确定序(按显示名、再按 `analyte_key`)。
/// 全部点都无日期的序列不出现在结果里 —— 见 [`is_renderable`]。
Future<List<TrendSeriesDto>> viewTrends() =>
    RustLib.instance.api.crateApiVaultProjectionsViewTrends();

/// **应急卡**:过敏史 + 在用药 + 确诊慢病,每项都带来源 document_id。
///
/// 血型恒为 None:当前抽取链路(`parser`)里没有血型抽取,输出 None 是如实说
/// 「我们不知道」。急救场景下编一个血型是会出人命的,宁可空着让人去问。
Future<EmergencyCardDto> viewEmergencyCard() =>
    RustLib.instance.api.crateApiVaultProjectionsViewEmergencyCard();

/// **就诊摘要单**:一屏能看完的结构化版(给 UI 渲染)+ 纯文本版(给「复制给医生」)。
///
/// 内容:基本信息 + 过敏史 + 在用药 + 最近关键化验(带日期与 flag)+ 我最近的变化 +
/// 我想问医生的(笔记)+ 最近就诊记录标题。全部是原文逐字内容、从原文抽出的数值/
/// 日期,或患者自己写的笔记(笔记单独标注,见 [`VisitNoteDto`])——**不生成任何
/// 解释性文字或结论**。
Future<VisitSummaryDto> viewVisitSummary() =>
    RustLib.instance.api.crateApiVaultProjectionsViewVisitSummary();

/// 一条在用药。
class ActiveMedDto {
  final String name;
  final String? atc;

  /// 最近一次提到的剂量(如 `"0.5g bid"`);没识别到剂量时为 None。
  final String? dose;

  /// 最早/最晚一次带日期的提及,`"YYYY-MM-DD"`;没有任何带日期的提及时为 None。
  final String? since;
  final String? until;

  /// 提到这个药的全部文档 id,升序去重。
  final Int64List documentIds;

  const ActiveMedDto({
    required this.name,
    this.atc,
    this.dose,
    this.since,
    this.until,
    required this.documentIds,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      atc.hashCode ^
      dose.hashCode ^
      since.hashCode ^
      until.hashCode ^
      documentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveMedDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          atc == other.atc &&
          dose == other.dose &&
          since == other.since &&
          until == other.until &&
          documentIds == other.documentIds;
}

/// 一条过敏史。`substance`/`reaction` 都是**报告原文逐字**片段。
class AllergyItemDto {
  final String substance;

  /// 括号里的反应描述(如 `"皮疹"`);原文只写了物质名时为空串。
  final String reaction;

  /// 提到这条过敏史的全部文档 id,升序去重。
  final Int64List documentIds;

  const AllergyItemDto({
    required this.substance,
    required this.reaction,
    required this.documentIds,
  });

  @override
  int get hashCode =>
      substance.hashCode ^ reaction.hashCode ^ documentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AllergyItemDto &&
          runtimeType == other.runtimeType &&
          substance == other.substance &&
          reaction == other.reaction &&
          documentIds == other.documentIds;
}

/// 一条确诊慢病。`term` 是病历原文逐字的诊断名。
class ChronicConditionDto {
  final String term;

  /// 最早一次带日期的提及,`"YYYY-MM-DD"`;都没日期时为 None。
  final String? onset;

  /// 病历自己印在诊断旁的 ICD 编码(如有)。
  final String? icdCode;

  /// 提到这条诊断的全部文档 id,升序去重。
  final Int64List documentIds;

  const ChronicConditionDto({
    required this.term,
    this.onset,
    this.icdCode,
    required this.documentIds,
  });

  @override
  int get hashCode =>
      term.hashCode ^ onset.hashCode ^ icdCode.hashCode ^ documentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChronicConditionDto &&
          runtimeType == other.runtimeType &&
          term == other.term &&
          onset == other.onset &&
          icdCode == other.icdCode &&
          documentIds == other.documentIds;
}

/// 应急卡:过敏史 + 在用药 + 确诊慢病,每一项都带来源。
class EmergencyCardDto {
  /// **恒为 None** —— 当前的抽取链路(`parser`)没有血型抽取,宁可留空也不编。
  /// 见本文件 [`view_emergency_card`] 的说明。
  final String? bloodType;
  final List<AllergyItemDto> allergies;
  final List<ActiveMedDto> activeMeds;
  final List<ChronicConditionDto> conditions;

  const EmergencyCardDto({
    this.bloodType,
    required this.allergies,
    required this.activeMeds,
    required this.conditions,
  });

  @override
  int get hashCode =>
      bloodType.hashCode ^
      allergies.hashCode ^
      activeMeds.hashCode ^
      conditions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmergencyCardDto &&
          runtimeType == other.runtimeType &&
          bloodType == other.bloodType &&
          allergies == other.allergies &&
          activeMeds == other.activeMeds &&
          conditions == other.conditions;
}

/// 序列上的一个观测点。
class TrendPointDto {
  /// **日精度** `"YYYY-MM-DD"`(取自文档的临床日期)。这一份报告没能定出日期时为
  /// None —— 这样的点画不到时间轴上,UI 应跳过它;但它仍带 `document_id`,原件照样
  /// 可达(`docs/007_UI_Guidelines.md` §2.1「原件永远可达」)。整条序列**全部**点都
  /// 无日期时该序列根本不会出现在结果里,见 [`is_renderable`]。
  final String? date;
  final double value;
  final String? unit;

  /// 化验单上的异常标记,通常是 `"H"` / `"L"`;没有标记时为 None。
  final String? flag;

  /// 这个点来自哪份文档 —— **真正的 document_id**,可直接喂
  /// `api::vault::get_document` / `read_source_bytes` 跳回原件。
  final PlatformInt64 documentId;

  const TrendPointDto({
    this.date,
    required this.value,
    this.unit,
    this.flag,
    required this.documentId,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      value.hashCode ^
      unit.hashCode ^
      flag.hashCode ^
      documentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrendPointDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          value == other.value &&
          unit == other.unit &&
          flag == other.flag &&
          documentId == other.documentId;
}

/// 一条化验序列的**全保真**投影(趋势图)。与 `ProxyLabDto` 的区别:点不截断、
/// 日精度、每点带 `flag` 与 `document_id`,并带上 `analyte_key`/`loinc` 供 UI 做
/// 同一指标的跨来源合并/跳转。
class TrendSeriesDto {
  /// 显示名:能归一化到词典时是规范中文名,否则是化验单上的原始名
  /// (`parser::AnalyteSeries::group_name`)。
  final String name;

  /// 归一化后的内部规范键(如 `"creatinine"`);未能归一化时为 None
  /// —— 未归一化的序列**绝不与已归一化的合并**,这是 `parser::aggregate` 的分组约定。
  final String? analyteKey;
  final String? loinc;

  /// 序列级单位:取**最后一个点**的单位,与 `handoff::series_to_json` 同一取法。
  ///
  /// 单位是 `parser::aggregate` 定下的**显示基准**单位 —— 绝大多数情况就是化验单
  /// 上逐字印的那个(患者要拿 app 上的数去核对手里那张纸);只有一条线上混了不同
  /// 印刷单位时才是规范单位,此时 [`Self::values_converted`] 为 `true`。
  /// 详见 `packages/parser/src/aggregate.rs` 模块头的「哪一层用哪一套单位」。
  final String? unit;

  /// 参考区间,**与 [`TrendPointDto::value`] 同单位**(`parser` 侧的硬不变量:
  /// 保证不了就整体留空)。UI 拿它画参考带 —— 带子和点必须同一个单位。
  final double? refLow;
  final double? refHigh;

  /// 这条线上混了不同印刷单位,值和参考区间**已统一换算**到规范单位。
  ///
  /// `true` 时 UI **必须说出来**:用户在自己那张化验单上找不到屏幕上这个数字,
  /// 不说等于改写原文(`docs/007` §2.1「原件永远可达」「不改写原文」)。
  /// `false`(常态)= 屏幕上的数值/单位/区间就是纸上印的那一套。
  final bool valuesConverted;

  /// 任一点被标记 H/L(`parser::AnalyteSeries::any_abnormal`)。
  final bool anyAbnormal;

  /// 这条序列所属的**检验大类**(化验单项目组表头,如「血常规」「肝功能」——
  /// 见 `terminology::panel_for` / `packages/terminology/panel_methodology.md`),
  /// 是 [`view_trend_panel_catalog`] 目录里的一个值,或 `None`。**只给一个**
  /// (不像疾病泳道允许多重归属:一项化验在真实报告单上只印在一个项目组表头
  /// 下)。`None` 表示这条序列没能归一化出 `analyte_key`,或归一化到的条目在
  /// 词典里没配 panel(专科/低频检验,如实留空而不是硬凑)—— 两种情况 UI 都
  /// 归入「其他」。
  final String? panel;

  /// **全部**观测点,按时间升序(无日期的排最后)。不做任何数量裁剪。
  final List<TrendPointDto> points;

  /// 这条序列是不是手动录入的自测值(血压/血糖/体重/体温/心率,「记录」入口
  /// 产出,而非从化验单 OCR 出来的)——`parser::AnalyteSeries::self_measured`
  /// 透传。自测序列结构上永远不会与同名医院序列合并(`aggregate` 的分组约定,
  /// 见 MANUAL-ENTRY-DESIGN.md),这个字段只用于**显示**:UI 据此加"(家测)"
  /// 标注 / 换个点形状,不改变哪些点属于这条序列。
  final bool selfMeasured;

  const TrendSeriesDto({
    required this.name,
    this.analyteKey,
    this.loinc,
    this.unit,
    this.refLow,
    this.refHigh,
    required this.valuesConverted,
    required this.anyAbnormal,
    this.panel,
    required this.points,
    required this.selfMeasured,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      analyteKey.hashCode ^
      loinc.hashCode ^
      unit.hashCode ^
      refLow.hashCode ^
      refHigh.hashCode ^
      valuesConverted.hashCode ^
      anyAbnormal.hashCode ^
      panel.hashCode ^
      points.hashCode ^
      selfMeasured.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrendSeriesDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          analyteKey == other.analyteKey &&
          loinc == other.loinc &&
          unit == other.unit &&
          refLow == other.refLow &&
          refHigh == other.refHigh &&
          valuesConverted == other.valuesConverted &&
          anyAbnormal == other.anyAbnormal &&
          panel == other.panel &&
          points == other.points &&
          selfMeasured == other.selfMeasured;
}

/// 摘要单上的一行化验:一个具体的测量点。
class VisitLabDto {
  final String name;

  /// `"YYYY-MM-DD"`。只收带日期的点,故必有值。
  final String date;

  /// 值 / 单位 / 参考区间三者**同单位**,来自 `parser::aggregate` 定下的显示基准
  /// (见那里的「哪一层用哪一套单位」)。常态下就是化验单上逐字印的那一套。
  final double value;
  final String? unit;
  final String? flag;
  final double? refLow;
  final double? refHigh;

  /// 见 [`TrendSeriesDto::values_converted`] —— 同一份透传。`true` 时这一行的
  /// 数值在患者手里那张纸上找不到,UI 必须标注「已统一换算」。
  final bool valuesConverted;
  final PlatformInt64 documentId;

  /// 见 `TrendSeriesDto::self_measured` 的文档 —— 同一份透传,就诊单据此在
  /// 「复制给医生」纯文本里追加"(家测)"(`render_plain_text`)。
  final bool selfMeasured;

  const VisitLabDto({
    required this.name,
    required this.date,
    required this.value,
    this.unit,
    this.flag,
    this.refLow,
    this.refHigh,
    required this.valuesConverted,
    required this.documentId,
    required this.selfMeasured,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      date.hashCode ^
      value.hashCode ^
      unit.hashCode ^
      flag.hashCode ^
      refLow.hashCode ^
      refHigh.hashCode ^
      valuesConverted.hashCode ^
      documentId.hashCode ^
      selfMeasured.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisitLabDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          date == other.date &&
          value == other.value &&
          unit == other.unit &&
          flag == other.flag &&
          refLow == other.refLow &&
          refHigh == other.refHigh &&
          valuesConverted == other.valuesConverted &&
          documentId == other.documentId &&
          selfMeasured == other.selfMeasured;
}

/// 就诊摘要单「我想问医生的」一节的一条笔记。
///
/// ## 为什么不进 [`VisitSummaryDto::plain_text`] 或二维码分享
///
/// 笔记是患者自己写的自由文本("今天头晕""问王医生片子的事"),不是从病历原文
/// 抽出来的。这一屏其它每一节都可以说"这是原文逐字"或"这是从原文抽出的数值/
/// 日期";笔记不行——它是患者此刻的主观记录,混进给医生的那份文本,读起来会
/// 被当成一条病历陈述(甚至被当成主诉)。所以它只出现在这一屏上,给患者自己看,
/// 提醒"待会儿要问这个"。二维码分享走的是 `packages/parser::handoff::assemble_summary`
/// 那条完全不同的管线(结构化的 problems/labs/meds,没有"最近文档"这种原文转述),
/// 笔记原本就到不了那里,这条边界是**结构性的**,不需要额外过滤。
///
/// ## 为什么没有"已经问过医生"这种已读标记
///
/// `MANUAL-ENTRY-DESIGN.md` §5.4 提过一个更细的方案:录入笔记时加一个"要问医生"
/// 的勾选标记,只有勾了的笔记才进这一节。这需要在笔记文本里编码一个隐藏标记(见
/// 该文档 §3.2 自测值的"结构化载荷"先例)——但笔记的 OCR 文本在这个项目里是一条
/// 反复强调的不变量:「逐字来自你的记录」,`note_never_becomes_a_condition_or_a_lab_series`
/// 这类测试钉的就是这条保真度。往里面塞一个显示时要再摘掉的隐藏前缀,是在为了一个
/// UI 分类去弄脏这条不变量,且没有历史笔记的回填路径(老笔记永远没有这个标记)。
/// 权衡下来选了更简单的退路:直接显示**最近几条**笔记(见
/// [`VISIT_SUMMARY_MAX_NOTES`]),不分类。代价是"今天头晕"和"问王医生片子的事"
/// 会混在一起,好处是零 core-model/parser 改动、老笔记立刻可用、没有退化的空标记
/// 语义。
class VisitNoteDto {
  /// 笔记原文,逐字。
  final String text;

  /// 记录时间,`"YYYY-MM-DD"`。录入弹层的"测量时间"对笔记同样必填,实践中恒有
  /// 值,但仍按 `Option` 处理,不假设。
  final String? date;
  final PlatformInt64 documentId;

  const VisitNoteDto({required this.text, this.date, required this.documentId});

  @override
  int get hashCode => text.hashCode ^ date.hashCode ^ documentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisitNoteDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          date == other.date &&
          documentId == other.documentId;
}

/// 摘要单上的一行就诊记录 —— 一个就诊组,或一份不属于任何就诊的独立文档。
class VisitRecordDto {
  /// 就诊组标题 / 文档标题;识别不到标题时为 None。
  final String? title;

  /// 就诊组:`inpatient|outpatient|emergency|exam`;独立文档:该文档的
  /// `doc_type`(如 `lab_report`)。
  final String kind;

  /// `"YYYY-MM-DD"`;没有日期时为 None。
  final String? date;

  /// 这条记录涵盖的文档 id(就诊组含组内全部文档)。
  final Int64List documentIds;

  const VisitRecordDto({
    this.title,
    required this.kind,
    this.date,
    required this.documentIds,
  });

  @override
  int get hashCode =>
      title.hashCode ^ kind.hashCode ^ date.hashCode ^ documentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisitRecordDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          kind == other.kind &&
          date == other.date &&
          documentIds == other.documentIds;
}

/// 就诊摘要单:结构化版(给 UI 渲染)+ 纯文本版(给「复制给医生」)。
class VisitSummaryDto {
  final PatientProfileDto patient;
  final List<AllergyItemDto> allergies;
  final List<ActiveMedDto> activeMeds;

  /// 最近的关键化验:每条序列取**最新一个带日期的点**,按日期倒序,最多
  /// [`VISIT_SUMMARY_MAX_LABS`] 条。完整序列在趋势页。**这一屏不单独渲染这份
  /// 全量列表**(2026-08-05 改版后只显示 [`recent_changes`]),它只喂
  /// [`plain_text`]——复制给医生的那份要带全的最近化验,不只是异常的那几条。
  final List<VisitLabDto> recentLabs;

  /// 「我最近的变化」:[`recent_labs`] 里自测的(`self_measured`)或**确为异常**
  /// (`flag` 是 `H`/`L`)的那些,最多 [`VISIT_SUMMARY_MAX_CHANGES`] 条,**不是**
  /// 从 [`recent_labs`] 截出来的——见 [`view_visit_summary`] 里的说明,共享同一个
  /// 8 条上限会把自测值挤没。只进这一屏的 UI,不进 [`plain_text`]/二维码分享
  /// (那两处已经有更完整的化验数据,不需要再复述一遍"哪些变了")。
  final List<VisitLabDto> recentChanges;

  /// 最近就诊/文档,最多 [`VISIT_SUMMARY_MAX_VISITS`] 条。
  final List<VisitRecordDto> recentVisits;

  /// 「我想问医生的」:最近的手动笔记,最多 [`VISIT_SUMMARY_MAX_NOTES`] 条,
  /// 按记录时间倒序。**只进这一屏,患者自己看**——见 [`VisitNoteDto`] 文档,
  /// 绝不进 [`plain_text`] 或二维码分享。
  final List<VisitNoteDto> recentNotes;

  /// 与上面结构化字段**同源同内容**的纯文本渲染,供直接复制给医生。
  /// 只含原文逐字内容 + 字段标签,不含任何解释、结论或推断,**且不含笔记**——
  /// 笔记是患者自由文本,混进给医生的这份容易被当成病历内容(见
  /// [`VisitNoteDto`] 文档)。
  final String plainText;

  const VisitSummaryDto({
    required this.patient,
    required this.allergies,
    required this.activeMeds,
    required this.recentLabs,
    required this.recentChanges,
    required this.recentVisits,
    required this.recentNotes,
    required this.plainText,
  });

  @override
  int get hashCode =>
      patient.hashCode ^
      allergies.hashCode ^
      activeMeds.hashCode ^
      recentLabs.hashCode ^
      recentChanges.hashCode ^
      recentVisits.hashCode ^
      recentNotes.hashCode ^
      plainText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisitSummaryDto &&
          runtimeType == other.runtimeType &&
          patient == other.patient &&
          allergies == other.allergies &&
          activeMeds == other.activeMeds &&
          recentLabs == other.recentLabs &&
          recentChanges == other.recentChanges &&
          recentVisits == other.recentVisits &&
          recentNotes == other.recentNotes &&
          plainText == other.plainText;
}
