// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dto.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_demo_files`, `detected_name_for`, `doc_summary`, `fmt_value`, `ingest_one`, `machine_device_id`, `open_resilient_with_fallback`, `parse_measured_at`, `resolve_vault_paths`, `self_measured_label`, `self_measured_title`, `vault_cell`, `with_state_mut`, `with_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `VaultState`

/// 打开(或新建)保险箱。iCloud 容器路径由 **Dart 侧经 MethodChannel 解析后传入**
/// (`icloud_container_dir`,容器根目录;不可用/非 iOS 传 `None`)——避免 Rust 框架
/// 反向链接 app target 的 Swift 符号(Flutter 插件框架不允许,会 archive linker 失败)。
///
/// 是否用 iCloud 布局以持久标记 `<data_dir>/icloud_enabled` 为准(enable/disable 写/删)。
/// 开了标记且传入了容器 → 真相在 `<container>/Documents/vault`、派生库在沙盒;否则本机
/// `<docs_dir>/vault`。在解析出的 truth_root 打开失败则回退本机,绝不因 iCloud 问题崩。
Future<void> openVault({
  required String docsDir,
  required String dataDir,
  String? icloudContainerDir,
}) => RustLib.instance.api.crateApiVaultOpenVault(
  docsDir: docsDir,
  dataDir: dataDir,
  icloudContainerDir: icloudContainerDir,
);

/// 健康档案时间线:就诊组 + 独立文档,按日期倒序(无日期最后)。与桌面/Tauri
/// 移动端的 `load_archive` 同构——复用同一套 core-model 查询。
Future<List<TimelineGroupDto>> loadArchive() =>
    RustLib.instance.api.crateApiVaultLoadArchive();

/// 文档详情:类型/日期 + 来源文件 + 识别文本。与桌面/Tauri 移动端的
/// `get_document` 同构。
Future<DocumentDetailDto> getDocument({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiVaultGetDocument(id: id);

/// 一份来源文件在磁盘上的**绝对路径**(CAS `objects/…` 下的对象文件)。
///
/// 供 iOS「查看原件」路径在读盘前先把可能被 iCloud 逐出的对象物化到本地用:Dart
/// 拿到此路径后经 `medme/icloud` MethodChannel 触发 `startDownloadingUbiquitousItem`
/// 并等待下载完成(见 `AppDelegate.swift` 的 `ensureDownloaded`),再调
/// `read_source_bytes` / `render_dicom_png` 读盘。安卓无 iCloud、不走这一步。
Future<String> sourceFileObjectPath({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiVaultSourceFileObjectPath(id: id);

/// 一份来源文件的原始字节(图片文档据此渲染缩略图/大图)。与桌面/Tauri 移动端的
/// `read_source_bytes` 同构。iOS 上保险箱开了 iCloud 同步时,`objects/` 里的对象可能
/// 被 iCloud 逐出(替换为 `.icloud` 占位符);Dart 侧在调用本函数前已按平台先经
/// `source_file_object_path` + `medme/icloud`.`ensureDownloaded` 把对象物化回本地,
/// 故这里保持一次普通读盘(已在本地的对象即快路径,不触发任何网络/下载)。
Future<Uint8List> readSourceBytes({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiVaultReadSourceBytes(id: id);

/// 渲染一份 DICOM 来源文件的锚点切片为 PNG。
///
/// 安全:`apps/mobile_flutter/rust/Cargo.toml` 给 iOS + 安卓两端都关掉了 `dicom`
/// 的 `codecs` 特性(C/C++ JPEG2000/JPEG-LS 解码器,GHSA-24px 的 RCE 面),与
/// Tauri 移动端 `apps/mobile/src-tauri/Cargo.toml` 的取舍完全一致——桌面才需要
/// 子进程隔离渲染(`dicom_subprocess`),移动端直接用 `medme_share` 提供的进程内
/// 渲染器就是安全的(其文档明确写了这点)。不支持的压缩格式返回错误,前端按现有
/// 「无法预览」的降级处理即可。
Future<Uint8List> renderDicomPng({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiVaultRenderDicomPng(id: id);

/// 删除一份文档(用户在 review 队列 / 时间线 / 详情页移除)。追加 `DocumentDeleted`
/// 事件 + 重放,原始字节留在 CAS(见 core-model `delete_document`)。文档不存在 = no-op。
/// 前端删完 `bumpVaultRevision` 刷新即可。
Future<void> deleteDocument({required PlatformInt64 documentId}) =>
    RustLib.instance.api.crateApiVaultDeleteDocument(documentId: documentId);

/// 患者档案头(姓名/性别/年龄/记录数)。与桌面/Tauri 移动端同构。
Future<PatientProfileDto> patientProfile() =>
    RustLib.instance.api.crateApiVaultPatientProfile();

/// 采集:对一个真实文件路径(如系统文件选择器返回的路径)跑 ingest,然后重建
/// 就诊分组。PDF/TXT/DICOM 走 `pipeline::ingest`。
Future<ImportOutcomeDto> ingestFile({required String path}) =>
    RustLib.instance.api.crateApiVaultIngestFile(path: path);

/// 采集(字节直传):Flutter 侧从相机/相册/文件选择器拿到的字节 + 原始文件名。
/// 落到沙盒 data 目录下的一次性临时文件(保留扩展名——`pipeline::mime_for` 靠
/// 扩展名判 MIME/PDF/DICOM)→ 跑 ingest → 重建分组 → 删临时文件。镜像 Tauri 版
/// `ingest_bytes`,只是临时文件目录用 `data_dir`(FRB 没有 `app_cache_dir()`)。
Future<ImportOutcomeDto> ingestBytes({
  required String filename,
  required List<int> data,
}) => RustLib.instance.api.crateApiVaultIngestBytes(
  filename: filename,
  data: data,
);

/// 扫描版 PDF 的逐页 OCR 回填。`ingest_bytes`/`ingest_pdf`(Rust pipeline)对
/// 缺文本层的页只能给出 `IngestOutcome::pages_without_text`(移动端未链接 Rust
/// OCR 引擎,那些页落库时压根没能 OCR),文档可能已建好(部分页有文本层)、也
/// 可能整份 `stored_no_text`(一页可用文本都没有)。Flutter 侧用 `pdfx` 把
/// `pages_without_text` 里点名的那些页逐一渲染成 PNG、走原生图片 OCR(iOS
/// Vision / 安卓 ML Kit)拿到文本后,逐页调本函数把文本补进该文档。
///
/// `page_no` 是 1-based、对应 PDF 里的真实页码(与 `pages_without_text` 的口径
/// 一致)——不再固定写 1:一份文档现在可能有多条 `ocr_result`(每页一条,
/// `core_model::Vault::add_ocr` 按 `(document_id, page_no)` 天然去重/幂等),
/// `ocr_text` 读取时按页码拼接。只补 `ocr_result`;`doc_type` 暂沿用建档时的
/// 分类(用 OCR 文本重分类属质量提升,另做)。文本为空则报错(调用方不应回填空)。
Future<void> backfillPdfText({
  required PlatformInt64 documentId,
  required int pageNo,
  required String text,
  required double confidence,
}) => RustLib.instance.api.crateApiVaultBackfillPdfText(
  documentId: documentId,
  pageNo: pageNo,
  text: text,
  confidence: confidence,
);

/// 采集(图片,Flutter 端已识别好文本):原始字节先入 CAS(与 `pipeline::ingest`
/// 一致,去重同一张图);识别出文字则建 document + ocr_result(backend 按编译目标
/// 如实标注 `MOBILE_OCR_BACKEND`——iOS=PP-OCRv5/Onnx,安卓=ML Kit;置信度取调用方
/// 传入值);识别为空则退回文件名元数据(`StoredNoText`),原件仍可见。落库语义逐字
/// 镜像 Tauri 版 `ingest_image_via_vision`/`ingest_image_via_mlkit`,只是识别文本来自
/// 参数而非本地再跑一次 OCR。
Future<ImportOutcomeDto> ingestImageWithText({
  required String name,
  required List<int> bytes,
  required String ocrText,
  required double confidence,
}) => RustLib.instance.api.crateApiVaultIngestImageWithText(
  name: name,
  bytes: bytes,
  ocrText: ocrText,
  confidence: confidence,
);

/// 写一条自测记录(结构化,append-only)。血压两个值(收缩压+舒张压)共享
/// 同一份文档/同一个 `measured_at` —— 一次测量是最小操作单元,一起删一起改
/// (MANUAL-ENTRY-DESIGN.md §5.3);其余四项(心率/体重/体温/血糖)各自单独一条
/// 记录一份文档。`measured_at` 缺省(`None`)= 写入时刻,否则调用方传用户选择
/// 的测量时间(RFC3339)。
///
/// 与 DICOM/txt 导入同构(见 `pipeline::add_text_layer_document`/
/// `pipeline::dicom_summary` 的先例):没有原件,把合成文本本身当"文件"过一遍
/// `vault.import`,再走 `add_document`+`add_ocr`。`doc_type` 固定
/// `SelfMeasurement`,不经 `parser::classify` 猜 —— 这条录入路径的类型是
/// 确定的,不需要也不该走给不确定文本猜类型的那条推断。
///
/// 硬约束(设计文档反复强调):**不支持任意化验项**——`values` 里的
/// `analyte_key` 由 Dart 侧封闭五选一界面产出,这里不做白名单校验(校验属于
/// UI 层拒绝非法输入的职责),但也不会因为一个陌生 key 而崩:未知 key 落进
/// `parser::home_ref_range` 的 `_ => None` 分支,裸值显示、不出 flag。
Future<PlatformInt64> addSelfMeasurement({
  required List<SelfMeasuredValueDto> values,
  String? measuredAt,
}) => RustLib.instance.api.crateApiVaultAddSelfMeasurement(
  values: values,
  measuredAt: measuredAt,
);

/// 读回一份 `self_measurement` 文档的结构化值 —— 供「编辑」预填表单用(编辑=
/// 删除旧文档+重新走一遍 `add_self_measurement`,见 MANUAL-ENTRY-DESIGN.md
/// §3.6:没有专门的编辑 API,复用现成的 `delete_document`+新增)。
///
/// 读不出结构化载荷(文档不是这个类型 / 载荷损坏)→ 空列表,调用方按「没有可
/// 编辑的值」处理,不猜(与 `parser::parse_self_measurement_payload` 同一条
/// "读不出就是没有,不半猜"的规矩)。
Future<List<SelfMeasuredValueDto>> selfMeasurementValues({
  required PlatformInt64 documentId,
}) => RustLib.instance.api.crateApiVaultSelfMeasurementValues(
  documentId: documentId,
);

/// 写一条笔记(纯文本自由文字)。原文即内容 —— 不需要 `self_entry` 那层结构化
/// 载荷编码(那是给数值用的),`ocr_result.text` 直接是用户输入的原文,读回来
/// 就是它本身。`doc_type` 固定 `Note`,不解析、不关联到具体用药/诊断
/// (`aggregate()` 对 `note` 类型文档显式跳过 meds/conditions 抽取)。
///
/// 与 [`add_self_measurement`] 同构:没有原件,把这段文字本身当"文件"过一遍
/// `vault.import`。`measured_at` 缺省 = 写入时刻。
Future<PlatformInt64> addNote({required String text, String? measuredAt}) =>
    RustLib.instance.api.crateApiVaultAddNote(
      text: text,
      measuredAt: measuredAt,
    );

/// 端到端加密分享:复用 `medme_share::share::build_encrypted_share`,把全部病历
/// 面对面二维码分享:把「当下病情」压成一条 URL,由手机端渲染成二维码给医生扫。
///
/// 与 [`create_share`] 的分工:那个是**整份病历**(含原件、影像,给医生带走);
/// 这个是**当下病情**(在治的病、关键指标最近几个点、在用的药),只够医生三十秒
/// 看懂大局 —— 要看原件或阅片,患者手机当场翻。
///
/// 载荷有界(见 `medme_share::qr::QrLimits`),因此体积与病历总量无关,永远塞得进
/// 一张二维码。密钥在 URL 的 `#` 之后,按 HTTP 规范不会发给服务器 —— 医生扫码后
/// 只从我们的静态页下载一个空壳查看器,病历数据全程只在两台手机之间。
Future<QrShareDto> buildQrShareUrl({required String baseUrl}) =>
    RustLib.instance.api.crateApiVaultBuildQrShareUrl(baseUrl: baseUrl);

/// 打包成自包含加密 HTML 写进保险箱 `shares/` 目录,返回口令、记录数、字节数与
/// 文件路径。与桌面/Tauri 移动端同构;安全性说明见 `render_dicom_png` 的 doc
/// (进程内 DICOM 渲染在移动端是安全的,`codecs` 特性已关)。
Future<ShareResultDto> createShare({required PlatformInt64 expiresDays}) =>
    RustLib.instance.api.crateApiVaultCreateShare(expiresDays: expiresDays);

/// 当前进程里打开的是哪个保险箱(真相根目录的绝对路径)。
///
/// 存在的理由是**医生代拍**:开一个代拍病人的箱子会顶掉进程级 vault,写入类调用
/// (ingest / create_proxy_share)必须能在动手前确认「此刻开着的确实是这个病人的
/// 箱子」——把「谁先 await 谁后 await」这种靠不住的约定,换成一次可验证的比对。
/// 见 Dart 侧 `ensureProxyVaultOpen`。
Future<String> currentVaultRoot() =>
    RustLib.instance.api.crateApiVaultCurrentVaultRoot();

/// 出码用的密文:整份病历(含原件),交给 Dart 传上瞬时云。
///
/// 返回 `(密文, base64url 密钥, 记录数)`。拿到对象 id 后二维码内容是
/// `<查看器>/#q2.<id>.<密钥>` —— 八十来个字符,格子稀疏、隔着桌子好扫。
///
/// **密钥不上传**,只进二维码的 `#` 之后。云上那份我们自己也解不开。
Future<(Uint8List, String, PlatformInt64)> qrShareBlob({
  required PlatformInt64 expiresDays,
}) => RustLib.instance.api.crateApiVaultQrShareBlob(expiresDays: expiresDays);

/// 代拍交付用的密文:**带同意书**、按已确认份数筛选摘要,交给 Dart 传上瞬时云。
///
/// 与 [`qr_share_blob`] 是同一种产物、同一套查看器解密逻辑,差别只有两处:这里带
/// 病人签过字的同意书,并且摘要只统计医生逐份确认过的那些(未确认的原件仍全在包里
/// 并标注待确认)。
///
/// 返回 `(密文, base64url 密钥, 记录数)`。拿到对象 id 后认领链接是
/// `https://medmenow.com/claim/#c1.<id>.<密钥>` —— 病人点开先在浏览器看,再决定存不存。
///
/// **密钥不上传**,只进链接的 `#` 之后。云上那份我们自己也解不开。
Future<(Uint8List, String, PlatformInt64)> proxyClaimBlob({
  required PlatformInt64 expiresDays,
  required ConsentDto consent,
  required Int64List confirmedIds,
}) => RustLib.instance.api.crateApiVaultProxyClaimBlob(
  expiresDays: expiresDays,
  consent: consent,
  confirmedIds: confirmedIds,
);

/// 认领:把医生代拍的加密包还原进**当前打开的**保险箱。
///
/// `blob` 是从瞬时云取回的密文,`key_b64` 是认领链接 `#` 后面那把钥匙 —— 两者都由
/// Dart 侧拿到后传进来,Rust 不联网(取密文是 Dart 的事,这里只管解密与落盘)。
///
/// 写的是「当前打开的箱子」,所以调用前必须已经切到病人自己要存进去的那个成员。
Future<ClaimResultDto> claimImport({
  required List<int> blob,
  required String keyB64,
}) => RustLib.instance.api.crateApiVaultClaimImport(blob: blob, keyB64: keyB64);

/// 只解密、不落盘:让病人在「存进哪个成员」之前先看到这包里有几份、是谁的。
/// 返回 `(记录数, 患者姓名)`;姓名解析不出时为空串。
Future<(PlatformInt64, String)> claimPreview({
  required List<int> blob,
  required String keyB64,
}) =>
    RustLib.instance.api.crateApiVaultClaimPreview(blob: blob, keyB64: keyB64);

/// 代拍(医生模式)专用的加密分享:与 [`create_share`] 只差两点 —— **把拍前同意
/// 记录打进加密包**、且只打包医生逐份确认过的文档。底下与临时会话版
/// `ephemeral_create_share` 调**同一个** `build_encrypted_share_with_consent_and_confirmed`,
/// 产出格式同构。
///
/// 确认状态由调用方(Dart 侧 `ProxyPatientManager`)传入而不是像临时会话那样存在
/// Rust 进程内存里:代拍病人要在本机保留 12 小时、跨 app 重启存活,内存 map 活不了
/// 那么久。Rust 侧不落盘确认状态 = 不动保险箱格式(不新增事件类型)。
Future<ShareResultDto> createProxyShare({
  required PlatformInt64 expiresDays,
  required ConsentDto consent,
  required Int64List confirmedIds,
}) => RustLib.instance.api.crateApiVaultCreateProxyShare(
  expiresDays: expiresDays,
  consent: consent,
  confirmedIds: confirmedIds,
);

/// 代拍审阅屏的「病情摘要卡」:对**当前打开的**保险箱(= 某个代拍病人的箱子)跑
/// 与 `ephemeral_summary` 同一套装配,只把 `confirmed_ids` 里的文档喂进去。
/// 复用 `vault_ephemeral` 的取文档/映射两个 helper,不另写一套排序与字段映射。
Future<ProxySummaryDto> proxySummary({required Int64List confirmedIds}) =>
    RustLib.instance.api.crateApiVaultProxySummary(confirmedIds: confirmedIds);

/// 导出时间线:复用 `medme_share::export::build_timeline_html_ranged`,把时间线
/// 渲染成未加密、可打印的自包含 HTML 写进保险箱 `shares/` 目录(与加密分享共用
/// 同一目录——都是本机生成、交给系统分享 sheet 的临时导出件)。
///
/// `from_date` / `to_date` 为可选的 `YYYY-MM-DD`(前端日期选择器传入);任一为空
/// 表示该侧不限,两者都为空即全量导出。`from` 取当天 00:00、`to` 取当天 23:59:59
/// (含端点)。无 `doc_date` 的记录仅在完全不筛选时纳入(见共享 crate 的说明)。
Future<ExportResultDto> exportTimelineHtml({
  String? fromDate,
  String? toDate,
}) => RustLib.instance.api.crateApiVaultExportTimelineHtml(
  fromDate: fromDate,
  toDate: toDate,
);

/// 一键「载入示例数据」:把编译进本 crate 的张建国示例病历(见 `DEMO_DATA`)
/// 批量导入保险箱,让测试者无需手动选文件就能看到 健康档案。按路径排序保证
/// 可复现;`pipeline::ingest` 去重,重复点击安全。返回成功处理的文件数。
///
/// 与 Tauri 版的差异只在「示例数据从哪来」:Tauri 版随 `bundle.resources` 打包、
/// 运行时用 `resource_dir()` 定位;这里没有「应用资源目录」,数据集直接编译进
/// 二进制(`DEMO_DATA`),运行时落一份到 `data_dir` 下的临时目录再喂给
/// `pipeline::ingest`(它按路径操作,不接受内存字节),用完即删。
Future<PlatformInt64> loadDemoData() =>
    RustLib.instance.api.crateApiVaultLoadDemoData();

/// 「清空保险箱 · 重置」:删掉当前真相目录(`truth_root`)+ 派生库
/// (`db_path`),再用 `open_split_resilient` 在同一位置重建。之后 `load_archive`
/// 会返回空。与桌面/Tauri 移动端的 `reset_vault` 同构,包括同一条安全兜底:
/// `truth_root` 必须是一个名为 `vault` 的目录,防止误删沙盒其它内容。
Future<void> resetVault() => RustLib.instance.api.crateApiVaultResetVault();

/// iCloud 同步是否已在本设备开启(读持久标记 `<data_dir>/icloud_enabled`)。
///
/// 分工:`enabled` 由 Rust 据持久标记如实返回;`available`(能否解析到 iCloud 容器)
/// 是 iOS-only 且需原生 API,Rust 拿不到容器,恒返回 `false` 交由 Dart 侧经
/// `medme/icloud` MethodChannel(`IcloudBridge.containerPath`)判断后覆盖。整套 iCloud
/// 开关/迁移逻辑见 `enable_icloud_sync` / `disable_icloud_sync` 与 `open_vault`。
Future<IcloudStatusDto> icloudStatus() =>
    RustLib.instance.api.crateApiVaultIcloudStatus();

/// 开启 iCloud 同步:把保险箱真相迁进 iCloud 容器 `<container_dir>/Documents/vault`,
/// 派生库留沙盒,写持久标记。容器路径由 Dart 经 MethodChannel 解析后传入。迁移用
/// core-model `relocate_to`(搬 objects/log/db/VERSION;容器里已有别设备的 vault 则
/// adopt+merge)——与已验证的 Tauri #38 同一套安全操作。幂等。
Future<void> enableIcloudSync({required String containerDir}) => RustLib
    .instance
    .api
    .crateApiVaultEnableIcloudSync(containerDir: containerDir);

/// 关闭 iCloud 同步:把真相从容器**复制**回本机 `<docs_dir>/vault`(容器副本保留),
/// 本地重开派生库,清标记 + 沙盒 iCloud 派生库。用 `copy_to` 只复制不删源。幂等。
Future<void> disableIcloudSync() =>
    RustLib.instance.api.crateApiVaultDisableIcloudSync();

/// 非 iOS/安卓构建(桌面/CLI)的占位实现。FRB codegen 在开发机上跑一次生成
/// `frb_generated.rs` + Dart 绑定,这份生成文件不按平台分叉,所以这个函数签名
/// 必须在所有 target 上都存在;函数体在非 iOS/安卓直接报错即可 —— `ocr` 依赖
/// 本身按 `cfg(pp_ocr)` 门控(见 `build.rs` 的规则与
/// `Cargo.toml`),桌面/CLI 构建压根不链接 oar-ocr/onnxruntime,这个分支不产生
/// 任何额外体积或依赖。
Future<OcrPpResultDto> recognizeImagePp({required List<int> bytes}) =>
    RustLib.instance.api.crateApiVaultRecognizeImagePp(bytes: bytes);
